### ISSUE TITLE
Website social link?

### ISSUE THREAD

**Issue by markphelps** [github/personal-website#101]
Maybe a duplicate of #96 , not sure..

Would it be possible to create a social type link for `website`? I realize that some may argue that this 'personal-website' might intend to act as that 'website'.. however I think it would be great to have the option to link to another website such as an already existing blog of the developer.

**Comment by aadibajpai** [comment]
Good idea, it could use a generic website icon.

**Comment by markphelps** [comment]
Yup! or perhaps even an generic globe icon such as https://fontawesome.com/icons/globe?style=solid ?

**Comment by aadibajpai** [comment]
Yeah that's I had in mind. But then you'd have to add your website directly in the social_media.yml instead of config.yml 🤔
