### ISSUE TITLE
Medium Username un-parsable in in config.yml

### ISSUE THREAD

**Issue by arora-aditya** [github/personal-website#102]
If I put a username according to the README.md i.e. with the `@` sign
```
social_media:
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  # linkedin: your_username
  medium: @ageitgey
  # stackoverflow: your_user_id
  # telegram: your_username
  # twitter: your_username
  # youtube: your_username
  # vk: your_username
```
I get the following error

```console
jekyll 3.7.4 | Error:  (/Users/myusername/Desktop/personal/personal-website/_config.yml): found character that cannot start any token while scanning for the next token at line 35 column 11
```

This seems to be because of the `@` sign in the config.yml which is un-parseable by Jekyll

If you remove the `@` symbol from your username then the link is rendered to a 404

![Screen Shot 2019-03-19 at 6 06 03 PM](https://user-images.githubusercontent.com/10962267/54645210-af0aef00-4a71-11e9-93a3-3526132c25c8.png)

**Comment by aadibajpai** [comment]
Put " " around it

**Comment by arora-aditya** [comment]
Shouldn't the readme reflect the same?

**Comment by aadibajpai** [comment]
There's already an open PR for the same #90
