### ISSUE TITLE
Display repositories contributed to

### ISSUE THREAD

**Issue by SUPERCILEX** [github/personal-website#110]
I mostly make contributions to pre-existing repositories, so my projects section is pretty bland. It'd be nice to be able to add arbitrary repositories we want to showcase and support pulling repositories where we have contributor access or have had a PR merged.

**Comment by BaileyJM02** [comment]
This does sound like a good idea however I think this project is very limited and tightly bound to the [Jekyll Github](http://jekyll.github.io/github-metadata/) plugin and as you can see, there are very few endpoints available. You can always see if it's possible to [contribute](https://github.com/jekyll/github-metadata) to the plugin.

**Comment by ghjansen** [comment]
I miss this feature and also something like #32. In fact, any information related to contributions would be of a great value in the personal website. Is there a plan to support this out of the box any time soon?

**Comment by SUPERCILEX** [comment]
Closing in favor of #83.
