### ISSUE TITLE
Sub-lists are not displayed properly

### ISSUE THREAD

**Issue by flamendless** [github/personal-website#114]
```
* Foo
    * Bar
```

Does not display correctly (no indentation). Ive tried different variations like new line before or after, use spaces instead of tabs, etc etc. None worked

**Comment by landonp1203** [comment]
@flamendless Can you show a bit more with some context?  A screenshot to see the issue and the code associated with it would be a good start. (HTML, liquid, etc.)

**Comment by flamendless** [comment]
Right now no, not on my pc. But what shows is that the sublist (bullet) is in the same line (indentation) as its parent list. But the color of the bullet shows properly (i.e, black bullet for parent and white bullet for sublist)

**Comment by aadibajpai** [comment]
@flamendless where does this happen? In a blog-post?

**Comment by flamendless** [comment]
> @flamendless where does this happen? In a blog-post?

Yes, in a blog post

**Comment by landonp1203** [comment]
@flamendless Does all of the other markdown show correctly?

**Comment by flamendless** [comment]
Last issue that got fixed was the block quotes.

As for other MD elements, i will issue once i encounter

**Comment by phagara** [comment]
HTML is correct, it is the CSS that's causing this issue. Verified by disabling styles for the page (`View -> Page Style -> No Style` in Firefox).

**Comment by flamendless** [comment]
@phagara hi, there is still an issue.

```markdown
* Item 1
    * sub-item 1
    * sub-item 2
* Item 2
```
does not appear to work. What works is:
```markdown
* Item 1
//new line here
    * sub-item 1
    * sub-item 2
* Item 2
```
This leads to sublist having a newline after its parent list. also, doing this:
```markdown
* Item 1
//new line here
    * sub-item 1
    * sub-item 2
//new line here
//new line here
//new line here
* Item 2
```
still renders the same as without any new lines after the sublist which is not correct

**Comment by phagara** [comment]
> @phagara hi, there is still an issue.
> [...]
> still renders the same as without any new lines after the sublist which is not correct

Works just fine for me, even after rebasing my fork against current master here.

See the [example post](https://phagara.github.io/2019/01/29/hello-world/) and [its source](https://raw.githubusercontent.com/phagara/phagara.github.io/master/_posts/2019-01-29-hello-world.md) in my fork (both ordered and unordered list examples at the end of the file).
