### ISSUE TITLE
Include repo-card in post?

### ISSUE THREAD

**Issue by AdamSpannbauer** [github/personal-website#118]
Sorry if this isn't the best place to ask or if the solution is obvious to a web-dev (unlike me).

Whenever I write a blog post it is often directly tied to a GitHub repo.  When I do this I put in a sentence linking to the repo like: "The code related to this post can be found in [this repo]()".

I think it would be nice to instead include a repo-card that details all the info in the repo related to the post.

Something like:

> The code related to this post can be found in the below repo:
> <p align='center'>
> <img src=https://user-images.githubusercontent.com/16326083/56044990-57793f80-5d0e-11e9-9ab3-d16cd050aae1.png width=250px>
> </p>

Is it possible to leverage the current repo-card implementation to do this cleanly, and if yes, how?

**Comment by jameslvdb** [comment]
Great question! I'm not incredibly experienced with Jekyll/Liquid, so I have no idea if this is best practice, but I think I've got a solution. I structured this as closely as I could to how the repo-card is used on the home page. I'm doing is filtering `site.github.public_repositories` according to the `name` field and iterating through a collection with a single repo in it.

```
<div class="col-sm-6 col-md-12 col-lg-6 col-xl-4 mb-3">
  {% assign myrepo = site.github.public_repositories | where: 'name', 'jameslvdb.github.io' %}
  {% for repository in myrepo  %}
    {% include repo-card.html %}
  {% endfor %}
</div>
```

The div class is what is present in projects.html. Screenshot of the result is below.

<img width="424" alt="Screen Shot 2019-04-18 at 3 42 08 PM" src="https://user-images.githubusercontent.com/15623255/56390013-94eb3a80-61f0-11e9-842d-573d2b58e45f.png">

Hope this helps!
