### ISSUE TITLE
Newlines after * does not properly format

### ISSUE THREAD

**Issue by flamendless** [github/personal-website#120]
Hi, ive noticed that after using a bullet (*), any newlines after that won't show properly.
Example:
```
* point 1
* point 2




This text should be rendered far from the bullet, but it will be rendered just below the last bullet regardless
```

**Comment by phagara** [comment]
HTML is correct, it is the CSS that's causing this issue. Verified by disabling styles for the page (`View -> Page Style -> No Style in Firefox`).

**Comment by flamendless** [comment]
The css should be fixed though right? Not browser-side fix

**Comment by phagara** [comment]
> The css should be fixed though right? Not browser-side fix

Correct.
