### ISSUE TITLE
Projects/repos not updating

### ISSUE THREAD

**Issue by gnestor** [github/personal-website#128]
It appears that project/repo items only update when I push new commits. Is this expected?

Here's my website on Github Pages: https://www.grantnestor.com/

Here's my repos on Github: https://github.com/gnestor?tab=repositories

**Comment by BaileyJM02** [comment]
Yes, due to the fact that Github pages are static, it will only update when it gets re-built.

**Comment by gnestor** [comment]
Makes sense. Does anyone have a nice and easy solution for rebuilding and pushing to Github?

**Comment by BaileyJM02** [comment]
I don't have an automated one as of yet but I just update the README file every time I want to refresh. I just increment a value at the top:
`Forced Build Count: 4`

**Comment by mattbhenley** [comment]
@BaileyJM02 I still don't see it refresh after I update the README file or any file. Do you just go in and make a new commit?

**Comment by brandonrosage** [comment]
You don't even have to change a file:
```
git commit -m 'rebuild pages' --allow-empty
git push origin <branch-name>
```
