### ISSUE TITLE
update to my account?

### ISSUE THREAD

**Issue by okwme** [github/personal-website#16]
this may be a dumb question... but  
following instructions I get a build representing the account of user @github. I don't see anywhere in the `_config.yaml` where the github account should be updated to my own. I tried adding `site: okwme` but it didn't update the build with my content.

Where am I supposed to add which user to build off of?

**Comment by okwme** [comment]
i see, must have cloned from this branch instead of my fork

**Comment by dmoa** [comment]
why does this make a difference?
