### ISSUE TITLE
undefined method `map'

### ISSUE THREAD

**Issue by Fzwael** [github/personal-website#224]
Hello,
I tried to fork the project, it works fine with Github pages, but on my local I always get this error : 
```
jekyll 3.8.5 | Error:  undefined method `map' for false:FalseClass
Did you mean?  tap
```
The error seems to come from `{% include projects.html %}` in home.html (if I remove it the project compiles)
I never used Ruby so I don't really know what's wrong.
I'm using Ubuntu 18.04 with WSL.
Thanks for your help!

**Comment by lee-yunseok** [comment]
This need your GitHub access token. Add your token first when you type serve or build, like below.

YOUR-TOKEN bundle exec jekyll serve

**Comment by Fzwael** [comment]
@lee-yunseok Thanks 👍 I think that's the problem (my credentials weren't properly synced between my host & my WSL)

**Comment by lee-yunseok** [comment]
Yeah it's a problem, this error did not occur before.
