### ISSUE TITLE
Add repository language badge to repo-card

### ISSUE THREAD

**Issue by Ullaakut** [github/personal-website#24]
It would be neat to have the repository language information displayed on the repository cards, just like it is in Github.

<img width="160" alt="screenshot 2019-02-22 at 17 09 45" src="https://user-images.githubusercontent.com/6976628/53254891-b0403a80-36c4-11e9-95f4-a995c4cbce4e.png">

The repository API publishes that information in the form of a string, so to replicate GitHub's behavior I've had to write some ugly code by adding an if statement for each language:

```html
    {% if repository.language == "Go" %}
    <span class="repo-language-color mr-1" style="background-color:#00ADD8;"></span>
    <span class="ml-0" itemprop="programmingLanguage">Go</span>
    {% endif %}
```

It would be neat if somehow it was possible to have an equivalent to this that doesn't add much complexity, but I'm not sure if it's doable.

**Comment by ccsplit** [comment]
@Ullaakut  I ended up making a couple of changes to your original code to make it a little better using https://github.com/ozh/github-colors/blob/master/colors.json for the colors and then changing your above code to:

```html
    {% if repository.language %}
      <span class="repo-language-color mr-1" style="background-color:{{ site.data.colors[repository.language]["color"] }}"></span>
      <span class="ml-0" itemprop="programmingLanguage">{{ repository.language }}</span>
    {% endif %}
```

I will work on getting a PR in unless someone beats me to it.

**Comment by Ullaakut** [comment]
That's an awesome generic solution. I guess we could open a PR to add this by default, what do you think?

**Comment by ccsplit** [comment]
@Ullaakut, currently have PR#28 but might take a little bit for it to be merged to master.
