### ISSUE TITLE
Improve style by making stargazers and forks stick to bottom of repo card

### ISSUE THREAD

**Issue by Ullaakut** [github/personal-website#25]
Here is how GitHub repository cards are laid out:

<img width="364" alt="screenshot 2019-02-22 at 17 11 24" src="https://user-images.githubusercontent.com/6976628/53255029-0ad99680-36c5-11e9-889f-317b48ee12f3.png">

The language tag, stargazers and forks are sticking to the bottom of the card.

The current stylesheet that can be found in `assets/styles.scss` is not consistent with the GitHub layout.

In order to do that, I'd suggest making the repo cards `position: relative` and the `div` element containing the stargazers and forks `position: absolute; bottom: 10px` to achieve a similar look.

The result of doing that can be seen on [my fork](https://ullaakut.github.io/)

**Comment by aleccunningham** [comment]
Could you open a PR reflecting this change?
