### ISSUE TITLE
Link Broken

### ISSUE THREAD

**Issue by jatin-pahuja** [github/personal-website#267]
The link in the about section shows 404 error

**Comment by carlagesa** [comment]
> The link in the about section shows 404 error 

It means that the page was nit found. Try cheking the link for proper linkage

**Comment by jatin-pahuja** [comment]
@carlagesa yeah link was not found but i was hoping that it should point to something rather than having that link

**Comment by carlagesa** [comment]
Check if you have linked it to the correct index.html page
