### ISSUE TITLE
error 404 while accessing https://github.dev 

### ISSUE THREAD

**Issue by pytxt** [github/personal-website#275]
The github pages site for this repo seems to be down. https://github.dev redirects to https://github.com/codespaces/

**Comment by KartikChugh** [comment]
+1 as of Aug 26

**Comment by prakarsh7695** [comment]
+1 on 1st Oct,2020

**Comment by 4lgn** [comment]
Still down as of November 2020

**Comment by skullface** [comment]
Thanks for this bug report! We’ve removed references to `github.dev` as it indeed is now used for our Codespaces feature.
