### ISSUE TITLE
show contributions count or activity

### ISSUE THREAD

**Issue by daixiang0** [github/personal-website#32]
Can show contributions count or activity related info?

**Comment by Ullaakut** [comment]
You can embed them using the [github-calendar](https://github.com/IonicaBizau/github-calendar) library, but it will require tweaking if you want it to fit with your theme.

Out of the box though, this repository doesn't display your contribution count or activity feed.

**Comment by daixiang0** [comment]
I get it, i would ask a PR about it if possible.
