### ISSUE TITLE
Code highlight?

### ISSUE THREAD

**Issue by kunicmarko20** [github/personal-website#33]
I tried doing 

```
```lang ```
```

and

```
{% highlight lang %} {% endhighlight %}
```
but non of those worked, any suggestion?

**Comment by Ullaakut** [comment]
I had the same issue, and ended up using an embedded gist instead (see [example here](https://ullaakut.github.io/2018/06/13/rtspatt/)) as a workaround.

Would definitely nice if it was supported.

**Comment by kunicmarko20** [comment]
That is a good workaround, thank you!

**Comment by willoucom** [comment]
I may have another workaround (still researching)

- Add a theme to your `_config.yml`, i choose `theme: jekyll-theme-time-machine`
- Add this line in top of your `assets/styles.scss` after others imports : `@import "{{ site.theme }}";`
- (To preserve carriage return) Edit `_includes/header.html`, remove ` | strip_newlines` in line 7 or in `{% assign content = page.content | strip_newlines %}`

Result in dark theme:

![image](https://user-images.githubusercontent.com/4134696/53336033-655d3780-38fd-11e9-8bd7-514e070c54e5.png)
 
Should I create a PR ?

**Comment by kunicmarko20** [comment]
looks good, would love to see a PR.

**Comment by rawkode** [comment]
Is it not possible to add the Prism plugin?

**Comment by brandonrosage** [comment]
Is this issue addressed now that #37 has been merged?
