### ISSUE TITLE
404 error when clicking 'github.dev' link

### ISSUE THREAD

**Issue by fleventy-5** [github/personal-website#447]
The https://github.dev/ present in the about section leads to a 404 error when click.
![Screenshot at 2021-02-21 18-53-13](https://user-images.githubusercontent.com/78148524/108626584-dbf28880-7476-11eb-9094-b73a50e4a435.png)

**Comment by emleddin** [comment]
I agree this needs to be updated, but for now you can view it at https://github.github.io/personal-website/

**Comment by skullface** [comment]
Thanks for this bug report and the follow-up comment! We’ve removed references to `github.dev` as it indeed is now used for our Codespaces feature.
