### ISSUE TITLE
Rendered page tries to load styles.css via HTTP

### ISSUE THREAD

**Issue by drewbrew** [github/personal-website#47]
Hi, the CSS is broken on my fork of this repo. After looking in Chrome's dev tools, it appears that the rendered HTML is trying to load CSS via HTTP despite the domain being served via HTTPS.

Example: https://winstel.dev/ ([Repo](https://github.com/drewbrew/drewbrew.github.io))

Expected behavior: the `absolute_url` filter would return `https://winstel.dev/assets/styles.css`

Actual behavior: `http://winstel.dev/assets/styles.css`

Net result: CSS is broken with HTTPS-only enforced (as is required on .dev domains)

Thanks!

**Comment by drewbrew** [comment]
I did another push and this seems to have fixed it. Closing!

**Comment by kadoyau** [comment]
Same issue.
Change `absolute_url` in header.html to `relative_url` works for me.

**Comment by VictorBaudot** [comment]
Same problem here
