### ISSUE TITLE
No GitHub API authentication could be found. Some fields may be missing or have incorrect data.

### ISSUE THREAD

**Issue by abhisheksoni27** [github/personal-website#48]

**Comment by Ullaakut** [comment]
That's expected behavior, it's because it is running in your dev environment and not in a Github pages instance.

**Comment by abhisheksoni27** [comment]
Thanks for letting me know. I guess it should be documented somewhere.

**Comment by Hallborg** [comment]
I came here for the exact same reason. I guess I won't be the last one

**Comment by snwfdhmp** [comment]
I came here for the same reason 😕
