### ISSUE TITLE
Replace redirecting to / with Jekyll baseurl setting

### ISSUE THREAD

**Issue by pizzafox** [github/personal-website#50]
Currently, many URLs redirect you to `/`. This causes problems when the website isn't hosted at the root of a domain. For example, forks of this will be at `https://username.github.io/personal-website` and the root would be a different website or a 404 page.

You should utilize [Jekyll's `baseurl`](https://jekyllrb.com/docs/configuration/options/#serve-command-options) option instead.

**Comment by Ullaakut** [comment]
I'm not sure I understand. My fork is available at https://ullaakut.github.io and does not have any `/personal-website` URL.

Did you rename your fork to `yourname.github.io` like instructed in the documentation?

**Comment by pizzafox** [comment]
This is for people who already have a GitHub pages site named `username.github.io`. It's best practice to use the base URL setting.
