### ISSUE TITLE
How to keep my site up-to-date

### ISSUE THREAD

**Issue by hifocus** [github/personal-website#73]
There are new features to be added every day for this project, how would I keep my own site up-to-date with those features? Currently what I do is delete the fork then re-fork it... (I know this question sounds silly, but I can't find any descriptions in the README about this)

Furthermore, as #14 #21, I really hope we will able to show our preferred repositories, including repositories that are owned by other organisations.

Thanks for all that effort.

**Comment by aadibajpai** [comment]
https://help.github.com/en/articles/syncing-a-fork

**Comment by hifocus** [comment]
> https://help.github.com/en/articles/syncing-a-fork

Thank you. Is there any form to do this with web ui or github desktop?

**Comment by aadibajpai** [comment]
not sure, but you probably have git installed so you just need to copy the commands @hifocus

**Comment by hifocus** [comment]
> not sure, but you probably have git installed so you just need to copy the commands @hifocus

Thanks. I will close this now.
