### ISSUE TITLE
[BUG] Share card in blog post lists Social Media that does not have share URL

### ISSUE THREAD

**Issue by aadibajpai** [github/personal-website#74]
![image](https://user-images.githubusercontent.com/27063113/53985232-1f944080-4141-11e9-8ea5-f2c402ce9d5b.png)

Dribbble does not have a share url but it is still listed with the share URL for Twitter (e.g. https://dev.aadibajpai.me/2019/01/29/hello-world/)

Something like listing the social media if shareURL exists could be done. I wasn't sure of the right way to implement it myself 😶

**Comment by brandonrosage** [comment]
Great catch, @aadibajpai! I refactored the implementation of the "Share" feature in #75 to fix this. Merge it into your (sharp-looking) site and let me know if it solves your problems. 👍
