### ISSUE TITLE
Let the user pick their favorite SSG

### ISSUE THREAD

**Issue by smakosh** [github/personal-website#9]
Why not let the user pick the SSG they want like Hugo, Gatsby, Pelican....?

**Comment by brandonrosage** [comment]
I'd love to hear any proposals you have for integrating those choices into this project. One of the design principles with this project was to provide a codebase that, upon forking, could be deployed without any changes and be ready for the public to see out of the box. We got pretty darn close with the initial release.

I'm not certain how one could start with this codebase, be asked to make a one-click or one-line-of-code decision, and simply deploy. It seems to me that that choice would require some pretty sweeping changes to the code that powers the layouts, etc.

I'm hoping you can show me how it'd work 👍

**Comment by smakosh** [comment]
I was thinking about having separate branches for each SSG, all will be easy to customize and deploy, this can be mentioned on the docs to let anyone know that they can have the same design & functionality but with different SSGs.

**Comment by brandonrosage** [comment]
@smakosh I think the codebases for each SSG would vary so widely that they'd be far better off managed in separate repos. The "Issues" alone would be impossible to decipher -- which codebase is the users referring to?

They would be distinctly different projects and should therefore be distinct repos, no?

_Example_: [Octicons](https://github.com/primer/octicons/#libraries), with separate repos for each library it supports.

**Comment by smakosh** [comment]
Yes makes sense
