### ISSUE TITLE
Support for Portfolio page

### ISSUE THREAD

**Issue by flamendless** [github/personal-website#96]

**Comment by brandonrosage** [comment]
Could you expound on what exactly the requirements for a "portfolio page" would be?

**Comment by flamendless** [comment]
A different page that showcases author's work or projects that is not specific to github repositories. May also serve as CV.

**Comment by vaggelisifantis** [comment]
Why to add support for portfolio that's not specific to github repositories right into this?
You always can add a page and make it however you want such as Portfolio or CV.
[https://github.com/github/personal-website#adding-pages](https://github.com/github/personal-website#adding-pages)

**Comment by brandonrosage** [comment]
@flamendless If I understand you correctly, it sounds like you want a more generic presentation of any kind of work-related content. I think the purpose there is so broad and unique to each person that this repository could not be useful for those purposes. 

This repo's purpose is to do the heavy lifting of wiring up a Jekyll website to showcase your work (assuming much of it is on GitHub) without requiring you to go and gather each project's content. Beyond that, you're very welcome to hack your fork to display any type of content you like. Just write the HTML into the existing files 👍🏼
